//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillPayProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DueDate { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
